const APP_VERSION='1.2.0';
const backend=window.NexoraBackend;
const $=id=>document.getElementById(id);
let lang=localStorage.getItem('nexora_lang')||'km';
let selectedPlatform='all';
let identity=null, orders=[], tickets=[], wallet={balance:0};
const services=[
{id:'content-calendar',category:'content',platform:'all',price:12,min:1,max:20,name:{km:'ផែនការមាតិកាប្រចាំខែ',en:'Monthly Content Calendar'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ផែនការ 30 ថ្ងៃ',en:'30-day plan'},details:{km:'ផែនការមាតិកា 30 ថ្ងៃ សម្រាប់ Page ឬ Brand។',en:'A 30-day content planning package for a page or brand.'}},
{id:'short-video',category:'content',platform:'tiktok',price:9,min:1,max:50,name:{km:'ផែនការវីដេអូខ្លី TikTok',en:'TikTok Short-form Content Plan'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'10 វីដេអូ / កញ្ចប់',en:'10-video plan'},details:{km:'គំនិតវីដេអូខ្លី, Hook, Caption និង Posting Structure។',en:'Short-form ideas, hooks, captions and posting structure.'}},
{id:'meta-ads',category:'ads',platform:'facebook',price:18,min:1,max:10,name:{km:'ពិនិត្យ Meta Ads Campaign',en:'Meta Ads Campaign Review'},time:{km:'2–3 ថ្ងៃ',en:'2–3 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ក្នុងមួយ Campaign',en:'Per campaign'},details:{km:'ពិនិត្យ Campaign Structure, Targeting, Creative និង Measurement Plan។',en:'Review campaign structure, targeting, creative organization and measurement planning.'}},
{id:'youtube-seo',category:'analytics',platform:'youtube',price:15,min:1,max:10,name:{km:'ពិនិត្យ SEO ឆានែល YouTube',en:'YouTube Channel SEO Audit'},time:{km:'2 ថ្ងៃ',en:'2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ក្នុងមួយឆានែល',en:'Per channel'},details:{km:'ពិនិត្យ Title, Description, Thumbnail និង Discoverability។',en:'Audit titles, descriptions, thumbnails and discoverability.'}},
{id:'community',category:'community',platform:'all',price:14,min:1,max:12,name:{km:'ផែនការគ្រប់គ្រង Community',en:'Community Management Plan'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ផែនការប្រចាំសប្ដាហ៍',en:'Weekly plan'},details:{km:'ផែនការឆ្លើយតប Comment, FAQ និង Moderation។',en:'A response, FAQ and moderation framework.'}},
{id:'ig-captions',category:'content',platform:'instagram',price:10,min:1,max:50,name:{km:'កញ្ចប់ Caption Instagram',en:'Instagram Caption Pack'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'10 Posts / កញ្ចប់',en:'10-post pack'},details:{km:'Caption និងគំនិតមាតិកាសម្រាប់ Instagram Page ឬ Brand។',en:'Captions and content angles for an Instagram page or brand.'}},
{id:'telegram-plan',category:'analytics',platform:'telegram',price:11,min:1,max:20,name:{km:'ផែនការ Telegram Channel',en:'Telegram Channel Strategy'},time:{km:'2 ថ្ងៃ',en:'2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'Strategy Report',en:'Strategy report'},details:{km:'Content, retention និង cross-promotion strategy។',en:'Content, retention and cross-promotion strategy.'}},
{id:'traffic-audit',category:'analytics',platform:'website',price:16,min:1,max:20,name:{km:'Website Social Traffic Audit',en:'Website Social Traffic Audit'},time:{km:'2–3 ថ្ងៃ',en:'2–3 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'Audit Report',en:'Audit report'},details:{km:'ពិនិត្យ Social-to-Website Funnel និង Tracking Setup។',en:'Audit the social-to-website funnel and tracking setup.'}}
];
function msg(km,en){return lang==='km'?km:en}
function initials(v){return (v||'NX').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'NX'}
function money(v){return `$${Number(v||0).toFixed(2)}`}
function setLanguage(next){lang=next;document.documentElement.lang=lang;localStorage.setItem('nexora_lang',lang);document.querySelectorAll('[data-km][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderServices();renderOrders();renderTickets();setupIdentity()}
function setupIdentity(){if(!identity)return;const name=identity.displayName||identity.email?.split('@')[0]||'NexoraUser',init=initials(name);document.querySelectorAll('.avatar,.mini-user').forEach(x=>x.textContent=init);$('sidebarUser').textContent=msg(`អ្នកប្រើ៖ ${name}`,`User: ${name}`);$('topUserName').textContent=name;$('menuUserName').textContent=name;$('menuUserEmail').textContent=identity.email||'';$('accountAvatar').textContent=init;$('accountDisplay').textContent=name;$('accountEmail').textContent=identity.email||'';$('profileName').value=name;$('profileEmail').value=identity.email||'';$('fundUser').textContent=name}
function filteredServices(){const q=($('serviceSearch')?.value||'').toLowerCase().trim(),cat=$('categorySelect')?.value||'all';return services.filter(s=>(selectedPlatform==='all'||s.platform==='all'||s.platform===selectedPlatform)&&(cat==='all'||s.category===cat)&&(!q||s.name.km.toLowerCase().includes(q)||s.name.en.toLowerCase().includes(q)))}
function currentService(){return services.find(s=>s.id===$('serviceSelect')?.value)}
function renderServices(){const sel=$('serviceSelect');if(sel){const list=filteredServices();sel.innerHTML=list.map(s=>`<option value="${s.id}">${s.name[lang]} · ${money(s.price)}</option>`).join('')||`<option value="">${msg('មិនមានសេវាកម្ម','No matching services')}</option>`}const cards=$('serviceCards');if(cards)cards.innerHTML=services.map(s=>`<article class="service-card"><h3>${s.name[lang]}</h3><p>${s.details[lang]}</p><b>${money(s.price)}</b></article>`).join('');updateServiceDetails()}
function updateServiceDetails(){const s=currentService();if(!s){if($('charge'))$('charge').value='$0.00';return}const qty=Math.max(s.min,Math.min(s.max,Number($('quantity')?.value)||s.min));$('quantity').value=qty;$('avgTime').value=s.time[lang];$('charge').value=money(s.price*qty);$('rangeText').textContent=`Min: ${s.min} · Max: ${s.max}`;$('serviceTitle').textContent=s.name[lang];$('startTime').textContent=s.start[lang];$('speed').textContent=s.speed[lang];$('serviceDetails').textContent=s.details[lang]}
function openView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const label=document.querySelector(`.nav-item[data-view="${id}"] b`);if(label)$('currentViewLabel').textContent=label.textContent;if(innerWidth<981)$('sidebar')?.classList.add('closed')}
function renderWallet(){const balance=Number(wallet?.balance||0);['sidebarBalance','summaryBalance','fundBalance','dashBalance'].forEach(id=>{if($(id))$(id).textContent=money(balance)});$('summaryBackend').textContent=backend?.isConfigured?'Supabase':'Demo';$('backendModeLabel').textContent=backend?.isConfigured?'Supabase connected':'Demo mode'}
function renderOrders(){const box=$('ordersList');$('summaryOrders').textContent=orders.length;$('dashOrders').textContent=orders.length;if(!orders.length){box.className='empty-state';box.textContent=msg('មិនទាន់មាន Order ទេ។','No orders yet.');return}box.className='';box.innerHTML=orders.map(o=>{const s=services.find(x=>x.id===o.service_id)||{};return `<div class="order-item"><div><strong>#${o.id} · ${(s.name||{})[lang]||o.service_id}</strong><br>${o.link||''}</div><div>${o.quantity||1}</div><div class="status-chip">${o.status||'pending'}</div></div>`}).join('')}
function renderTickets(){const box=$('ticketList');$('ticketBadge').textContent=tickets.length;$('summaryTickets').textContent=tickets.length;$('dashTickets').textContent=tickets.length;if(!tickets.length){box.innerHTML=`<div class="empty-state">${msg('មិនទាន់មាន Ticket ទេ។','No tickets yet.')}</div>`;return}box.innerHTML=tickets.map(t=>`<article class="ticket-card"><div><strong>${t.subject}</strong><span>${t.status}</span></div><p>${t.message}</p></article>`).join('')}
async function loadData(){identity=await backend.getIdentity();if(!identity){location.replace('login.html');return}setupIdentity();try{[orders,tickets,wallet]=await Promise.all([backend.listOrders(),backend.listTickets(),backend.getWallet()]);orders=orders||[];tickets=tickets||[];wallet=wallet||{balance:0}}catch(e){console.error(e)}renderOrders();renderTickets();renderWallet();renderServices()}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
document.querySelectorAll('.platform').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.platform').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedPlatform=b.dataset.platform;renderServices()}));
$('menuToggle')?.addEventListener('click',()=>$('sidebar').classList.toggle('closed'));
$('profileMenuBtn')?.addEventListener('click',()=>$('profileMenu').classList.toggle('open'));
document.querySelectorAll('[data-action="account"]').forEach(b=>b.addEventListener('click',()=>{openView('account');$('profileMenu').classList.remove('open')}));
document.querySelectorAll('[data-action="logout"]').forEach(b=>b.addEventListener('click',async()=>{await backend.signOut();localStorage.removeItem('nexora_demo_user');location.href='login.html'}));
$('serviceSearch')?.addEventListener('input',renderServices);$('categorySelect')?.addEventListener('change',renderServices);$('serviceSelect')?.addEventListener('change',updateServiceDetails);$('quantity')?.addEventListener('input',updateServiceDetails);
$('submitOrder')?.addEventListener('click',async()=>{const s=currentService();if(!s)return;const link=$('projectLink').value.trim(),quantity=Number($('quantity').value)||1;if(!link){$('formNote').textContent=msg('សូមបញ្ចូល Link សាធារណៈ។','Enter a public link.');return}try{$('submitOrder').disabled=true;await backend.createOrderRequest({serviceId:s.id,link,quantity});orders=await backend.listOrders();renderOrders();$('formNote').textContent=msg('បានបង្កើត Order request ក្នុង Supabase។','Order request saved to Supabase.')}catch(e){$('formNote').textContent=e.message||msg('មានបញ្ហា។','Something went wrong.')}finally{$('submitOrder').disabled=false}});
$('ticketForm')?.addEventListener('submit',async e=>{e.preventDefault();const subject=$('ticketSubject').value.trim(),message=$('ticketMessage').value.trim();try{await backend.createTicket({subject,message});tickets=await backend.listTickets();renderTickets();e.target.reset();$('ticketNote').textContent=msg('Ticket ត្រូវបានរក្សាទុក។','Ticket saved.')}catch(err){$('ticketNote').textContent=err.message||msg('មិនអាចបង្កើត Ticket បាន។','Unable to create ticket.')}});
$('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const name=$('profileName').value.trim();if(name.length<2)return;try{const p=await backend.updateProfile(name);identity.displayName=p?.display_name||name;setupIdentity();$('profileNote').textContent=msg('បានរក្សាទុក។','Saved.')}catch(err){$('profileNote').textContent=err.message||msg('មិនអាចរក្សាទុកបាន។','Unable to save.')}});
setLanguage(lang);loadData();
