const services=[
{id:'content-calendar',category:'content',platform:'all',price:12,min:1,max:20,name:{km:'ផែនការមាតិកាប្រចាំខែ',en:'Monthly Content Calendar'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ផែនការ 30 ថ្ងៃ',en:'30-day plan'},scope:{km:'មាតិកា + កាលវិភាគ',en:'Content + schedule'},details:{km:'Link: Public page / project URL\nStart: Within 1 business day\nDelivery: 30-day planning package\nScope: Content ideas + publishing cadence\n\nចំណាំ៖ នេះជាសេវារៀបចំផែនការ។ មិនធានា Followers, Likes ឬ Engagement ទេ។',en:'Link: Public page / project URL\nStart: Within 1 business day\nDelivery: 30-day planning package\nScope: Content ideas + publishing cadence\n\nNote: This is a planning service. It does not guarantee followers, likes, reach or engagement.'}},
{id:'short-video',category:'content',platform:'tiktok',price:9,min:1,max:50,name:{km:'ផែនការវីដេអូខ្លី TikTok',en:'TikTok Short-form Content Plan'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'10 វីដេអូ / កញ្ចប់',en:'10-video plan'},scope:{km:'Hook + Caption + Idea',en:'Hooks + captions + ideas'},details:{km:'កញ្ចប់គំនិតវីដេអូខ្លីសម្រាប់ TikTok/Reels មាន Hook, Caption និង Posting Structure។',en:'A short-form video planning package for TikTok/Reels with hooks, captions and posting structure.'}},
{id:'meta-ads',category:'ads',platform:'facebook',price:18,min:1,max:10,name:{km:'ពិនិត្យ Meta Ads Campaign',en:'Meta Ads Campaign Review'},time:{km:'2–3 ថ្ងៃ',en:'2–3 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ក្នុងមួយ Campaign',en:'Per campaign'},scope:{km:'Setup + Creative Review',en:'Setup + creative review'},details:{km:'ពិនិត្យ Campaign Structure, Targeting, Creative និង Measurement Plan សម្រាប់ Meta Ads។',en:'Review campaign structure, targeting, creative organization and measurement planning.'}},
{id:'youtube-seo',category:'analytics',platform:'youtube',price:15,min:1,max:10,name:{km:'ពិនិត្យ SEO ឆានែល YouTube',en:'YouTube Channel SEO Audit'},time:{km:'2 ថ្ងៃ',en:'2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ក្នុងមួយឆានែល',en:'Per channel'},scope:{km:'SEO Audit Report',en:'SEO audit report'},details:{km:'ពិនិត្យ Title, Description, Thumbnail, Channel Structure និង Discoverability។',en:'Audit titles, descriptions, thumbnails, channel structure and discoverability.'}},
{id:'community',category:'community',platform:'all',price:14,min:1,max:12,name:{km:'ផែនការគ្រប់គ្រង Community',en:'Community Management Plan'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ផែនការប្រចាំសប្ដាហ៍',en:'Weekly plan'},scope:{km:'FAQ + Comment Framework',en:'FAQ + comment framework'},details:{km:'ផែនការឆ្លើយតប Comment, FAQ និង Moderation សម្រាប់ Page ឬ Brand។',en:'A response, FAQ and moderation framework for a page or brand.'}},
{id:'ig-captions',category:'content',platform:'instagram',price:10,min:1,max:50,name:{km:'កញ្ចប់ Caption Instagram',en:'Instagram Caption Pack'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'10 Posts / កញ្ចប់',en:'10-post pack'},scope:{km:'Caption + Content Angles',en:'Captions + content angles'},details:{km:'Caption 10 និងគំនិតមាតិកាសម្រាប់ Instagram Page ឬ Brand។',en:'Ten captions plus content angles for an Instagram page or brand.'}},
{id:'telegram-plan',category:'analytics',platform:'telegram',price:11,min:1,max:20,name:{km:'ផែនការ Telegram Channel',en:'Telegram Channel Strategy'},time:{km:'2 ថ្ងៃ',en:'2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'Strategy Report',en:'Strategy report'},scope:{km:'Organic Audience Plan',en:'Organic audience plan'},details:{km:'យុទ្ធសាស្ត្រមាតិកា Retention និង Cross-promotion តាមវិធីស្របច្បាប់។',en:'Content, retention and cross-promotion strategy for legitimate organic audience development.'}},
{id:'traffic-audit',category:'analytics',platform:'website',price:16,min:1,max:20,name:{km:'Website Social Traffic Audit',en:'Website Social Traffic Audit'},time:{km:'2–3 ថ្ងៃ',en:'2–3 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'Audit Report',en:'Audit report'},scope:{km:'Funnel + Tracking',en:'Funnel + tracking'},details:{km:'ពិនិត្យ Social-to-Website Funnel, Tracking Setup និង Landing Page Alignment។',en:'Audit the social-to-website funnel, tracking setup and landing-page alignment.'}}
];
let lang=localStorage.getItem('nexora_lang')||'km',selectedPlatform='all';const $=id=>document.getElementById(id),sidebar=$('sidebar'),category=$('categorySelect'),service=$('serviceSelect'),search=$('serviceSearch'),quantity=$('quantity');
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
let currentUser=readJson('nexora_demo_user',null);if(!currentUser)location.replace('login.html');const userId=()=>String(currentUser?.email||'guest').toLowerCase(),orderKey=()=>`nexora_demo_orders_${userId()}`,ticketKey=()=>`nexora_demo_tickets_${userId()}`;let demoOrders=readJson(orderKey(),[]),tickets=readJson(ticketKey(),[{subject:'Welcome to Nexora Support',message:'Your demo ticket center is ready.',status:'Open'}]);
function saveOrders(){localStorage.setItem(orderKey(),JSON.stringify(demoOrders))}function saveTickets(){localStorage.setItem(ticketKey(),JSON.stringify(tickets))}function initials(name){return(name||'NX').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'NX'}
function setupUser(){if(!currentUser)return;const name=currentUser.displayName||currentUser.email?.split('@')[0]||'NexoraUser',email=currentUser.email||'',init=initials(name);document.querySelectorAll('.avatar,.mini-user').forEach(el=>el.textContent=init);$('sidebarUser').textContent=lang==='km'?`អ្នកប្រើ៖ ${name}`:`User: ${name}`;$('topUserName').textContent=name;$('menuUserName').textContent=name;$('menuUserEmail').textContent=email;$('accountAvatar').textContent=init;$('accountDisplay').textContent=name;$('accountEmail').textContent=email;$('profileName').value=name;$('profileEmail').value=email}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-km][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('option[data-km][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('nexora_lang',lang);setupUser();refreshServices();renderOrders();renderServiceCards();renderTickets()}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;translate()}));$('menuToggle')?.addEventListener('click',()=>sidebar.classList.toggle('closed'));$('showMore')?.addEventListener('click',()=>{$('moreMenu').classList.toggle('open');$('showMore').classList.toggle('active')});
const viewLabels={'new-order':{km:'បញ្ជាទិញថ្មី',en:'New order'},orders:{km:'ការបញ្ជាទិញរបស់ខ្ញុំ',en:'My orders'},funds:{km:'បញ្ចូលទឹកប្រាក់',en:'Add funds'},services:{km:'សេវាកម្ម',en:'Services'},tickets:{km:'សំបុត្រជំនួយ',en:'Tickets'},'mass-order':{km:'បញ្ជាទិញច្រើន',en:'Mass order'},api:{km:'API',en:'API'},dashboard:{km:'ផ្ទាំងសង្ខេប',en:'Dashboard'},affiliates:{km:'ដៃគូ',en:'Affiliates'},'child-panel':{km:'Child panel',en:'Child panel'},faq:{km:'FAQ',en:'FAQ'},updates:{km:'បច្ចុប្បន្នភាព',en:'Updates'},terms:{km:'លក្ខខណ្ឌ',en:'Terms'},account:{km:'គណនីរបស់ខ្ញុំ',en:'My account'}};
function openView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('currentViewLabel').textContent=(viewLabels[id]||viewLabels['new-order'])[lang];if(innerWidth<981)sidebar.classList.add('closed')}
document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>openView(btn.dataset.view)));document.querySelectorAll('.platform').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.platform').forEach(x=>x.classList.remove('active'));btn.classList.add('active');selectedPlatform=btn.dataset.platform;refreshServices()}));
function filtered(){const q=search.value.trim().toLowerCase();return services.filter(s=>(selectedPlatform==='all'||s.platform==='all'||s.platform===selectedPlatform)&&(category.value==='all'||s.category===category.value)&&(!q||s.name.km.toLowerCase().includes(q)||s.name.en.toLowerCase().includes(q)))}function current(){return services.find(s=>s.id===service.value)}
function refreshServices(){const list=filtered();service.innerHTML=list.length?list.map(s=>`<option value="${s.id}">${s.name[lang]} · $${s.price.toFixed(2)}</option>`).join(''):`<option value="">${lang==='km'?'មិនមានសេវាកម្មត្រូវគ្នា':'No matching services'}</option>`;updateDetails()}
function updateDetails(){const s=current();if(!s){$('avgTime').value='';$('charge').value='$0.00';$('serviceDetails').textContent=lang==='km'?'មិនទាន់ជ្រើសសេវាកម្ម។':'No service selected.';return}const qty=Math.min(s.max,Math.max(s.min,Number(quantity.value)||s.min));quantity.value=qty;$('avgTime').value=s.time[lang];$('charge').value=`$${(s.price*qty).toFixed(2)}`;$('rangeText').textContent=`Min: ${s.min} · Max: ${s.max}`;$('startTime').textContent=s.start[lang];$('speed').textContent=s.speed[lang];$('guarantee').textContent=s.scope[lang];$('detailAvg').textContent=s.time[lang];$('serviceDetails').textContent=s.details[lang];$('exampleLink').textContent=lang==='km'?'តំណសាធារណៈរបស់ Page ឬ Project':'Public page or project URL'}
category?.addEventListener('change',refreshServices);search?.addEventListener('input',refreshServices);service?.addEventListener('change',updateDetails);quantity?.addEventListener('input',updateDetails);
$('submitOrder')?.addEventListener('click',()=>{const s=current();if(!s)return;const qty=Number(quantity.value)||1;demoOrders.unshift({serviceId:s.id,total:s.price*qty,link:$('projectLink').value.trim(),status:'demo',createdAt:new Date().toISOString()});saveOrders();renderOrders();$('formNote').textContent=lang==='km'?'បានបន្ថែមសំណើសាកល្បង។ មិនមានការទូទាត់ ឬ Order ពិតត្រូវបានផ្ញើទេ។':'Demo request added. No payment or real order was sent.'});
function renderOrders(){const box=$('ordersList'),total=demoOrders.reduce((a,o)=>a+Number(o.total||0),0);$('summaryOrders').textContent=demoOrders.length;$('summarySpend').textContent=`$${total.toFixed(2)}`;$('dashOrders').textContent=demoOrders.length;$('dashSpend').textContent=`$${total.toFixed(2)}`;const q=($('orderSearch')?.value||'').trim().toLowerCase(),list=demoOrders.filter(o=>{const s=services.find(x=>x.id===o.serviceId);return!q||(s?.name[lang]||'').toLowerCase().includes(q)||(o.link||'').toLowerCase().includes(q)});if(!list.length){box.className='empty-state';box.textContent=lang==='km'?'មិនទាន់មានការបញ្ជាទិញសាកល្បងទេ។':'No demo orders yet.';return}box.className='';box.innerHTML=list.map((o,i)=>{const s=services.find(x=>x.id===o.serviceId);return`<div class="order-item"><div><strong>#${String(demoOrders.length-i).padStart(4,'0')} · ${s?.name[lang]||'Service'}</strong><br><span>${o.link||(lang==='km'?'គ្មានតំណ':'No link')}</span></div><div>$${Number(o.total||0).toFixed(2)}</div><div class="status-chip">${lang==='km'?'សាកល្បង':'Demo'}</div></div>`}).join('')}
$('orderSearch')?.addEventListener('input',renderOrders);
function renderServiceCards(){const q=($('serviceCardSearch')?.value||'').trim().toLowerCase(),list=services.filter(s=>!q||s.name.km.toLowerCase().includes(q)||s.name.en.toLowerCase().includes(q));$('serviceCards').innerHTML=list.map(s=>`<article class="service-card"><span class="service-platform">${s.platform.toUpperCase()}</span><h3>${s.name[lang]}</h3><p>${s.details[lang].split('\n')[0]}</p><b>$${s.price.toFixed(2)}</b></article>`).join('')}$('serviceCardSearch')?.addEventListener('input',renderServiceCards);
function renderTickets(){$('ticketBadge').textContent=tickets.length;$('dashTickets').textContent=tickets.length;$('ticketList').innerHTML=tickets.length?tickets.map((t,i)=>`<article class="ticket-item"><strong>#T${String(i+1).padStart(3,'0')} · ${t.subject}</strong><span>${t.message}</span><span class="ticket-status">${t.status||'Open'}</span></article>`).join(''):`<div class="empty-state">${lang==='km'?'មិនមាន Ticket':'No tickets'}</div>`}
$('ticketForm')?.addEventListener('submit',e=>{e.preventDefault();const subject=$('ticketSubject').value.trim(),message=$('ticketMessage').value.trim();if(!subject||!message)return;tickets.unshift({subject,message,status:'Open'});saveTickets();renderTickets();e.target.reset()});document.querySelectorAll('.quick-funds button').forEach(btn=>btn.addEventListener('click',()=>{$('fundAmount').value=btn.dataset.amount}));
$('profileMenuBtn')?.addEventListener('click',e=>{e.stopPropagation();$('profileMenu').classList.toggle('open')});document.addEventListener('click',e=>{if(!$('profileMenu')?.contains(e.target)&&!$('profileMenuBtn')?.contains(e.target))$('profileMenu')?.classList.remove('open')});$('profileMenu')?.querySelector('[data-action="account"]')?.addEventListener('click',()=>{openView('account');$('profileMenu').classList.remove('open')});function logout(){localStorage.removeItem('nexora_demo_user');location.replace('login.html')}$('profileMenu')?.querySelector('[data-action="logout"]')?.addEventListener('click',logout);$('logoutButton')?.addEventListener('click',logout);
$('profileForm')?.addEventListener('submit',e=>{e.preventDefault();const name=$('profileName').value.trim();if(name.length<2)return;currentUser={...currentUser,displayName:name};localStorage.setItem('nexora_demo_user',JSON.stringify(currentUser));setupUser();$('profileStatus').textContent=lang==='km'?'បានរក្សាទុកឈ្មោះថ្មី។':'Profile name saved.'});translate();setupUser();renderOrders();renderTickets();