const services = [
  {id:'content-calendar',category:'content',platform:'all',price:12,min:1,max:20,name:{km:'ផែនការមាតិកាប្រចាំខែ',en:'Monthly Content Calendar'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ផែនការ 30 ថ្ងៃ',en:'30-day plan'},scope:{km:'មាតិកា + កាលវិភាគ',en:'Content + schedule'},details:{km:'Link: Public page / project URL\nStart: Within 1 business day\nDelivery: 30-day planning package\nScope: Content ideas + publishing cadence\n\nចំណាំសំខាន់៖\n• សេវានេះជាសេវារៀបចំផែនការ។\n• មិនធានា Followers, Likes ឬ Engagement ទេ។\n• កុំដាក់ព័ត៌មានសម្ងាត់ក្នុង Link ឬ Notes។',en:'Link: Public page / project URL\nStart: Within 1 business day\nDelivery: 30-day planning package\nScope: Content ideas + publishing cadence\n\nImportant notes:\n• This is a planning service.\n• It does not guarantee followers, likes, reach, or engagement.\n• Do not submit private credentials in links or notes.'}},
  {id:'short-video',category:'content',platform:'tiktok',price:9,min:1,max:50,name:{km:'ផែនការវីដេអូខ្លី TikTok',en:'TikTok Short-form Content Plan'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'10 វីដេអូ / កញ្ចប់',en:'10-video plan'},scope:{km:'Hook + Caption + Idea',en:'Hooks + captions + ideas'},details:{km:'កញ្ចប់គំនិតវីដេអូខ្លី សម្រាប់ TikTok/Reels មាន Hook, Caption និង Posting Structure។\n\nសម្រាប់មាតិកាស្របច្បាប់ និងការអភិវឌ្ឍគណនីតាមរបៀបធម្មតា។',en:'A short-form video planning package for TikTok/Reels with hooks, captions, and posting structure.\n\nDesigned for legitimate content strategy and organic account development.'}},
  {id:'meta-ads',category:'ads',platform:'facebook',price:18,min:1,max:10,name:{km:'ពិនិត្យ Meta Ads Campaign',en:'Meta Ads Campaign Review'},time:{km:'2–3 ថ្ងៃ',en:'2–3 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ក្នុងមួយ Campaign',en:'Per campaign'},scope:{km:'Setup + Creative Review',en:'Setup + creative review'},details:{km:'ពិនិត្យ Campaign Structure, Targeting, Creative និង Measurement Plan សម្រាប់ Meta Ads។',en:'Review campaign structure, targeting, creative organization, and measurement plan for Meta Ads.'}},
  {id:'youtube-seo',category:'analytics',platform:'youtube',price:15,min:1,max:10,name:{km:'ពិនិត្យ SEO ឆានែល YouTube',en:'YouTube Channel SEO Audit'},time:{km:'2 ថ្ងៃ',en:'2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ក្នុងមួយឆានែល',en:'Per channel'},scope:{km:'SEO Audit Report',en:'SEO audit report'},details:{km:'ពិនិត្យ Title, Description, Thumbnail, Channel Structure និង Discoverability។',en:'Audit titles, descriptions, thumbnails, channel structure, and discoverability.'}},
  {id:'community',category:'community',platform:'all',price:14,min:1,max:12,name:{km:'ផែនការគ្រប់គ្រង Community',en:'Community Management Plan'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'ផែនការប្រចាំសប្ដាហ៍',en:'Weekly plan'},scope:{km:'FAQ + Comment Framework',en:'FAQ + comment framework'},details:{km:'ផែនការឆ្លើយតប Comment, FAQ និង Moderation សម្រាប់ Page ឬ Brand។',en:'A response, FAQ, and moderation framework for a page or brand.'}},
  {id:'ig-captions',category:'content',platform:'instagram',price:10,min:1,max:50,name:{km:'កញ្ចប់ Caption Instagram',en:'Instagram Caption Pack'},time:{km:'1–2 ថ្ងៃ',en:'1–2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'10 Posts / កញ្ចប់',en:'10-post pack'},scope:{km:'Caption + Content Angles',en:'Captions + content angles'},details:{km:'Caption 10 និងគំនិតមាតិកាសម្រាប់ Instagram Page ឬ Brand។',en:'Ten captions plus content angles for an Instagram page or brand.'}},
  {id:'telegram-plan',category:'analytics',platform:'telegram',price:11,min:1,max:20,name:{km:'ផែនការ Telegram Channel',en:'Telegram Channel Strategy'},time:{km:'2 ថ្ងៃ',en:'2 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'Strategy Report',en:'Strategy report'},scope:{km:'Organic Audience Plan',en:'Organic audience plan'},details:{km:'យុទ្ធសាស្ត្រមាតិកា Retention និង Cross-promotion តាមវិធីស្របច្បាប់។',en:'Content, retention, and cross-promotion strategy for legitimate organic audience development.'}},
  {id:'traffic-audit',category:'analytics',platform:'website',price:16,min:1,max:20,name:{km:'Website Social Traffic Audit',en:'Website Social Traffic Audit'},time:{km:'2–3 ថ្ងៃ',en:'2–3 days'},start:{km:'ក្នុង 1 ថ្ងៃធ្វើការ',en:'Within 1 business day'},speed:{km:'Audit Report',en:'Audit report'},scope:{km:'Funnel + Tracking',en:'Funnel + tracking'},details:{km:'ពិនិត្យ Social-to-Website Funnel, Tracking Setup និង Landing Page Alignment។',en:'Audit the social-to-website funnel, tracking setup, and landing-page alignment.'}}
];
let lang='km', selectedPlatform='all', demoOrders=[];
const $=id=>document.getElementById(id);
const sidebar=$('sidebar'), category=$('categorySelect'), service=$('serviceSelect'), search=$('serviceSearch'), quantity=$('quantity');
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-km][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('option[data-km][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));refreshServices();renderOrders();renderServiceCards()}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;translate()}));
$('menuToggle').addEventListener('click',()=>sidebar.classList.toggle('closed'));
$('showMore').addEventListener('click',()=>{$('moreMenu').classList.toggle('open');$('showMore').classList.toggle('active')});
document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(btn.dataset.view)?.classList.add('active');if(innerWidth<981)sidebar.classList.add('closed')}));
document.querySelectorAll('.platform').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.platform').forEach(x=>x.classList.remove('active'));btn.classList.add('active');selectedPlatform=btn.dataset.platform;refreshServices()}));
function filtered(){const q=search.value.trim().toLowerCase();return services.filter(s=>(selectedPlatform==='all'||s.platform==='all'||s.platform===selectedPlatform)&&(category.value==='all'||s.category===category.value)&&(!q||s.name.km.toLowerCase().includes(q)||s.name.en.toLowerCase().includes(q)))}
function current(){return services.find(s=>s.id===service.value)}
function refreshServices(){const list=filtered();service.innerHTML=list.length?list.map(s=>`<option value="${s.id}">${s.name[lang]} · $${s.price.toFixed(2)}</option>`).join(''):`<option value="">${lang==='km'?'មិនមានសេវាកម្មត្រូវគ្នា':'No matching services'}</option>`;updateDetails()}
function updateDetails(){const s=current();if(!s){$('avgTime').value='';$('charge').value='$0.00';$('serviceDetails').textContent=lang==='km'?'មិនទាន់ជ្រើសសេវាកម្ម។':'No service selected.';return}const qty=Math.min(s.max,Math.max(s.min,Number(quantity.value)||s.min));quantity.value=qty;$('avgTime').value=s.time[lang];$('charge').value=`$${(s.price*qty).toFixed(2)}`;$('rangeText').textContent=`Min: ${s.min} · Max: ${s.max}`;$('startTime').textContent=s.start[lang];$('speed').textContent=s.speed[lang];$('guarantee').textContent=s.scope[lang];$('detailAvg').textContent=s.time[lang];$('serviceDetails').textContent=s.details[lang];$('exampleLink').textContent=lang==='km'?'តំណសាធារណៈរបស់ Page ឬ Project':'Public page or project URL'}
category.addEventListener('change',refreshServices);search.addEventListener('input',refreshServices);service.addEventListener('change',updateDetails);quantity.addEventListener('input',updateDetails);
$('submitOrder').addEventListener('click',()=>{const s=current();if(!s)return;const qty=Number(quantity.value)||1;demoOrders.unshift({service:s,total:s.price*qty,link:$('projectLink').value.trim()});renderOrders();$('formNote').textContent=lang==='km'?'បានបន្ថែមសំណើសាកល្បង។ មិនមានការទូទាត់ ឬ Order ពិតត្រូវបានផ្ញើទេ។':'Demo request added. No payment or real order was sent.'});
function renderOrders(){const box=$('ordersList');$('summaryOrders').textContent=` ${demoOrders.length}`;const total=demoOrders.reduce((a,o)=>a+o.total,0);$('summarySpend').textContent=` $${total.toFixed(2)}`;if(!demoOrders.length){box.className='empty-state';box.textContent=lang==='km'?'មិនទាន់មានការបញ្ជាទិញសាកល្បងទេ។':'No demo orders yet.';return}box.className='';box.innerHTML=demoOrders.map((o,i)=>`<div class="order-item"><div><strong>#${String(i+1).padStart(4,'0')} · ${o.service.name[lang]}</strong><br>${o.link||(lang==='km'?'គ្មានតំណ':'No link')}</div><div>$${o.total.toFixed(2)}</div><div class="status-chip">${lang==='km'?'សាកល្បង':'Demo'}</div></div>`).join('')}
function renderServiceCards(){$('serviceCards').innerHTML=services.map(s=>`<article class="service-card"><h3>${s.name[lang]}</h3><p>${s.details[lang].split('\n')[0]}</p><b>$${s.price.toFixed(2)}</b></article>`).join('')}
translate();
